apiVersion: ingress.karl.tech/v1beta1
kind: App
metadata:
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/instance: app-sample
    app.kubernetes.io/part-of: kubebuilder-demo
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubebuilder-demo
  name: app-sample
spec:
  # TODO(user): Add fields here
